services:
  jetson-container:
    image: ghcr.io/aris-space/project-polaris-docker:runtime
    container_name: jetson-container
    privileged: true
    network_mode: host
    # 1. Use the explicit NVIDIA runtime (crucial for Jetson)
    runtime: nvidia
    container_name: ${CONTAINER_NAME:-jetson-container}
    environment:
      - ROS_DOMAIN_ID=37
      - ROS_WS=/ros2_ws
      - CONTAINER_NAME=${CONTAINER_NAME:-jetson-container}
      - NTRIP_HOST=${NTRIP_HOST:-www.swipos.ch}
      - NTRIP_PORT=${NTRIP_PORT:-2101}
      - NTRIP_MOUNTPOINT=${NTRIP_MOUNTPOINT:-MSM_GISGEO_LV95LHN95}
      - NTRIP_USE_HTTPS=${NTRIP_USE_HTTPS:-false}
      - NTRIP_USERNAME=${NTRIP_USERNAME:-}
      - NTRIP_PASSWORD=${NTRIP_PASSWORD:-}
      - AUTO_BUILD=1
      - REFRESH_PY_PACKAGES=1
      - CLEAN_BUILD=0
      - ROSDEP_INSTALL=1
      # 2. These belong in Environment, not Devices
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/ros2_ws
      - ./recordings:/ros2_ws/recordings
      - /dev:/dev
      - ./mavlink_logs:/root/polaris_logs/
      - /home/polaris5:/home/polaris5
    working_dir: /ros2_ws
    entrypoint: [ "/bin/bash", "/ros2_ws/entrypoint.sh" ]
    stdin_open: true
    tty: true
    command: [ "bash", "-lc", "sleep infinity" ]
    restart: unless-stopped
