<?xml version="1.0"?>
<package format="3">
  <name>recorder_controller_node</name>
  <version>0.1.0</version>
  <description>ROS2 rosbag2 recorder controller for POLARIS Foxglove panel</description>
  <maintainer email="polaris@example.com">Polaris</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
