# prototype_gelb/Dockerfile.base
FROM ros:jazzy-ros-base

ENV PYTHONUNBUFFERED=1
WORKDIR /app

# System & ROS deps
RUN apt-get update && apt-get install -y --no-install-recommends \
      python3-pip \
      ros-jazzy-rclpy \
      ros-jazzy-mavros-msgs \
      ros-jazzy-sensor-msgs \
      pigpio python3-pigpio \
    && rm -rf /var/lib/apt/lists/*


# Python deps (still reading from src/requirements.txt in repo)
# COPY src/requirements.txt /app/src/requirements.txt
# RUN if [ -s /app/src/requirements.txt ]; then \
#      pip3 install --no-cache-dir -r /app/src/requirements.txt; \
#    fi

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
